Statement of Problem: To Predict Diabetes Given A Set of Symptoms

In [1]:
# Load relevant libraries :

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')            # Add to Cheat sheet

In [2]:
# Read data onto Jupyter notebook :
diabetes = pd.read_csv(r'C:\Users\user\Downloads\NB_diabetes.csv')
diabetes

glucose  bloodpressure  diabetes
0         40             85         0
1         40             92         0
2         45             63         1
3         45             80         0
4         40             73         1
..       ...            ...       ...
990       45             87         0
991       40             83         0
992       40             83         0
993       40             60         1
994       45             82         0

[995 rows x 3 columns]

In [3]:
# Create a copy for use in our analysis :
df = diabetes.copy()

In [4]:
# Check rows & columns :
df.shape

(995, 3)

In [5]:
# Check for missing values :
df.isnull().sum()

glucose          0
bloodpressure    0
diabetes         0
dtype: int64

In [6]:
# Split data into features and target :
X = df[['glucose','bloodpressure']]
y = df['diabetes']

In [7]:
# Checking for rows & columns :
print(X.shape)
print(y.shape)

(995, 2)
(995,)


In [8]:
# Creating arrays :
X = np.array(X)
y = np.array(y)

In [9]:
# Importing library for splitting data for training & testing:
from sklearn.model_selection import train_test_split


In [10]:
# Splitting data into train & test :
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 0.2, random_state = 42)

In [11]:
# Checking for rows & columns :
X_train.shape,X_test.shape 

((796, 2), (199, 2))

In [12]:
# Checking for rows & columns :
y_train.shape,y_test.shape

((796,), (199,))

In [13]:
# Importing library for Naive Bayes Classification:
from sklearn.naive_bayes import GaussianNB

In [14]:
# Creating model :
model = GaussianNB()

In [15]:
# Fitting model :
model.fit(X_train,y_train)

GaussianNB()

In [16]:
# Calculating model/ accuracy score:   
model.score(X_test,y_test)

0.9296482412060302

In [17]:
# Calculating model/ accuracy score:

In [18]:
#Predict the test set results
y_pred = model.predict(X_test)
y_test,y_pred

(array([1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
        1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
        0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
        0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
        0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
        0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1,
        0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
        0], dtype=int64),
 array([1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1,
        1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
        1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 1

In [19]:
from sklearn.metrics import accuracy_score
acc_sc = accuracy_score(y_test,y_pred)
acc_sc

0.9296482412060302

In [20]:
# ==== Application ===

In [21]:
# Making a prediction 
# Patient Test Results:
# glucose : 46 ; 
# blood pressure :75


In [22]:
patient1 = ([[46,75]])

In [23]:
prediction = model.predict(patient1)
prediction

array([1], dtype=int64)

In [24]:
# Patient Test Results:
# glucose : 40 ; 
# blood pressure :84

In [25]:
patient2 = ([[40,84]])

In [26]:
prediction = model.predict(patient2)
prediction

array([0], dtype=int64)