#### Training Sheet 1

In [149]:
# 1. Need to create a Cheat Sheet. ( To be reviewed bi-weekly).
# 2. Review & refreshing of Course. 
# 3. Raffle ,NYT,VSE,

In [150]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [151]:
 # !pip install -U numpy pandas scikit-learn

In [152]:
# print(f"Python: {sys.version}")
# print(f'NumPy: {np.__version__}')
# print(f'pandas: {pd.__version__}')
# print(f'scikit-learn: {sklearn.__version__}')

#### I. Dimension

In [153]:
# 1. A pandas DataFrame has two dimensions,i.e. the rows and the columns.

# Example :
staff = ['Albert','Brenda', 'Cecil','Diane']
age = [26, 21, 18, 30]
staff_age = pd.DataFrame({'staff':['Albert','Brenda', 'Cecil','Diane'],
                         'age':[26, 21, 18, 30]})
staff_age

staff  age
0  Albert   26
1  Brenda   21
2   Cecil   18
3   Diane   30

In [154]:
# 2. Checking the dimension :
df = staff_age.copy() 
df.ndim

2

#### II. Data Shape

In [155]:
# 1.The shape attribute shows the number of items in each dimension. 
df.shape

(4, 2)

#### III.Size

In [156]:
# 1. The size attribute shows how many cells there are.
df.size            # =>(4 x 2 = 8) 

8

#### IV. Pandas Series 

In [157]:
# 1. We can get a pandas series by slicing either column from the DataFrame:
df['staff']

0    Albert
1    Brenda
2     Cecil
3     Diane
Name: staff, dtype: object

In [158]:
# 2. Check the type :
type(df['staff'])

pandas.core.series.Series

In [159]:
# 3. What is the shape of a Series ?
a = df['staff']
a.shape

(4,)

In [160]:
# 4. This is a tuple with only the number of rows.

#### IV. DataFrame 

In [161]:
# 5. Let's repeat the same,but this time we use a list:
aa = df[['staff']]
aa

staff
0  Albert
1  Brenda
2   Cecil
3   Diane

In [162]:
# 5. cont'd :
type(aa)          # We now have a DataFrame

pandas.core.frame.DataFrame

In [163]:
# 6. Check for shape :
aa.shape   # (Dataframe with 4 rows and 1 column)

(4, 1)

#### NB :

#### VI. Numpy Array 

In [164]:
# 1. We use this function to convert to numpy array :  df.to_numpy()
# From earlier example =>
#2 a.
a = df['staff']
a_arr = a.to_numpy()
a_arr
# OR 

array(['Albert', 'Brenda', 'Cecil', 'Diane'], dtype=object)

In [165]:
#2 b.
df_arr = df['staff'].to_numpy()
df_arr
# Same result.

array(['Albert', 'Brenda', 'Cecil', 'Diane'], dtype=object)

In [166]:
# 3. Checking the shape :
print(a_arr.shape)
print(df_arr.shape)

(4,)
(4,)


#### Source of Problem :

In [167]:
# 1. Majority of scikit-learn transformers & estimators expect to be fed their predictive X data in two-dimensional form.
# 2. The target variable, y is expected to be one-dimensional.

#### Solution 1 To The Problem :

In [168]:
# First convert all string or text to numerals:

X.replace({'Albert':1,'Brenda':2,'Cecil':3,'Diane':4,},inplace =True)

In [169]:
# a.Just pass the columns as a list.=>( a DataFrame)
# i.e. instead of df['staff'] you do :
X = df[['staff']]
X

staff
0  Albert
1  Brenda
2   Cecil
3   Diane

In [170]:
X.replace({'Albert':1,'Brenda':2,'Cecil':3,'Diane':4,},inplace =True)
X

C:\Users\user\anaconda3_a\lib\site-packages\pandas\core\frame.py:4524: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().replace(


staff
0      1
1      2
2      3
3      4

In [171]:
X.shape  # You shave a dimensional variable.

(4, 1)

In [172]:
y = df[['age']]
y

age
0   26
1   21
2   18
3   30

In [173]:
y.shape

(4, 1)

In [174]:
from sklearn.linear_model import LinearRegression

ln = LinearRegression()

In [175]:
ln.fit(X,y)

LinearRegression()

In [176]:
print('Intercept is :',ln.intercept_)

Intercept is : [21.5]


In [177]:
# =====================================

#### Solution 2 To The Problem : reshape using (-1,1)

In [178]:
x = df['staff']
print(x)
print(x.shape)

0    Albert
1    Brenda
2     Cecil
3     Diane
Name: staff, dtype: object
(4,)


In [179]:
# replace text with numerals :
x.replace({'Albert':1,'Brenda':2,'Cecil':3,'Diane':4,},inplace =True)
x

0    1
1    2
2    3
3    4
Name: staff, dtype: int64

In [180]:
x1 = np.array(x)
x1

array([1, 2, 3, 4], dtype=int64)

In [181]:
x1.shape

(4,)

In [182]:
x1 = x1.reshape(-1,1)
x1

array([[1],
       [2],
       [3],
       [4]], dtype=int64)

In [183]:
y = df['age']
y
y.shape

(4,)

In [184]:
y1 = np.array(y)
y1

array([26, 21, 18, 30], dtype=int64)

In [185]:
y1 = y1.reshape(-1,1)
y1

array([[26],
       [21],
       [18],
       [30]], dtype=int64)

In [186]:
from sklearn.linear_model import LinearRegression

ln = LinearRegression()

In [187]:
x1.shape

(4, 1)

In [188]:
y1.shape

(4, 1)

In [189]:
ln.fit(x1,y1)

LinearRegression()

In [190]:
print('Intercept is :',ln.intercept_)

Intercept is : [21.5]
